<center><img src="MKn_Staffelter_Hof.jpeg" alt="Picture of old business"</center>
<!--Image Credit: Martin Kraft https://commons.wikimedia.org/wiki/File:MKn_Staffelter_Hof.jpg -->

Staffelter Hof Winery is Germany's oldest business, established in 862 under the Carolingian dynasty. It has continued to serve customers through dramatic changes in Europe, such as the Holy Roman Empire, the Ottoman Empire, and both world wars. What characteristics enable a business to stand the test of time?

To help answer this question, BusinessFinancing.co.uk researched the oldest company still in business in **almost** every country and compiled the results into several CSV files. This dataset has been cleaned.

Having useful information in different files is a common problem. While it's better to keep different types of data separate for data storage, you'll want all the data in one place for analysis. You'll use joining and data manipulation to work with this data and better understand the world's oldest businesses.

## The Data
`businesses` and `new_businesses`
|Column|Description|
|------|-----------|
|`business`|Name of the business (varchar)|
|`year_founded`|Year the business was founded (int)|
|`category_code`|Code for the business category (varchar)|
|`country_code`|ISO 3166-1 three-letter country code (char)|
---
`countries`
|Column|Description|
|------|-----------|
|`country_code`|ISO 3166-1 three-letter country code (varchar)|
|`country`|Name of the country (varchar)|
|`continent`|Name of the continent the country exists in (varchar)|
---
`categories`
|Column|Description|
|------|-----------|
|`category_code`|Code for the business category (varchar)|
|`category`|Description of the business category (varchar)|

In [7]:
-- What is the oldest business on each continent?
SELECT 
    c.continent, 
    c.country, 
    b.business, 
    b.year_founded
FROM countries AS c
INNER JOIN businesses AS b 
    ON c.country_code = b.country_code
WHERE (c.continent, b.year_founded) IN (
    SELECT 
        c2.continent, 
        MIN(b2.year_founded)
    FROM countries AS c2
    INNER JOIN businesses AS b2 
        ON c2.country_code = b2.country_code
    GROUP BY c2.continent
);

       continent    country                     business  year_founded
0         Africa  Mauritius               Mauritius Post          1772
1           Asia      Japan                   Kongō Gumi           578
2         Europe    Austria  St. Peter Stifts Kulinarium           803
3  North America     Mexico  La Casa de Moneda de México          1534
4  South America       Peru      Casa Nacional de Moneda          1565
5        Oceania  Australia               Australia Post          1809

In [8]:
-- How many countries per continent lack data on the oldest businesses
-- Does including the `new_businesses` data change this?
SELECT 
    c.continent,
    COUNT(c.country_code) AS countries_without_businesses
FROM countries AS c
LEFT JOIN (
    SELECT country_code FROM businesses
    UNION ALL
    SELECT country_code FROM new_businesses
) AS all_bus ON c.country_code = all_bus.country_code
WHERE all_bus.country_code IS NULL
GROUP BY c.continent;

       continent  countries_without_businesses
0  South America                             3
1        Oceania                            10
2         Africa                             3
3           Asia                             7
4  North America                             5
5         Europe                             2

In [9]:
-- Which business categories are best suited to last over the course of centuries?
SELECT 
    c.continent,
    cat.category,
    MIN(b.year_founded) AS year_founded
FROM countries AS c
INNER JOIN businesses AS b 
    ON c.country_code = b.country_code
INNER JOIN categories AS cat 
    ON b.category_code = cat.category_code
GROUP BY c.continent, cat.category;

        continent                           category  year_founded
0   North America                  Banking & Finance          1891
1            Asia                        Agriculture          1930
2          Africa                        Agriculture          1947
3   South America                   Food & Beverages          1660
4          Africa                             Mining          1962
5          Europe                            Medical          1422
6            Asia                 Telecommunications          1885
7            Asia                            Defense          1808
8            Asia                             Energy          1928
9            Asia               Aviation & Transport          1858
10  North America                        Agriculture          1638
11           Asia                     Postal Service          1800
12           Asia                  Banking & Finance          1830
13         Europe                              Media          1999
14  North America                             Retail          1670
15         Europe         Manufacturing & Production           864
16  South America                            Defense          1811
17  North America         Manufacturing & Production          1534
18         Africa               Aviation & Transport          1854
19  North America                              Media          1909
20           Asia                   Food & Beverages          1820
21        Oceania                     Postal Service          1809
22  South America                  Banking & Finance          1565
23         Europe                        Agriculture          1218
24           Asia         Manufacturing & Production          1736
25         Africa                             Energy          1968
26         Europe                             Mining          1248
27  North America                   Tourism & Hotels          1770
28           Asia  Distillers, Vintners, & Breweries          1853
29         Europe                 Telecommunications          1912
30         Europe                     Consumer Goods          1649
31           Asia                   Tourism & Hotels          1584
32         Europe                     Postal Service          1520
33         Africa                              Media          1943
34        Oceania                  Banking & Finance          1861
35         Europe  Distillers, Vintners, & Breweries           862
36         Africa                   Food & Beverages          1878
37  North America                   Food & Beverages          1920
38           Asia          Cafés, Restaurants & Bars          1153
39           Asia                              Media          1931
40         Africa                     Postal Service          1772
41         Africa  Distillers, Vintners, & Breweries          1933
42         Africa         Manufacturing & Production          1820
43           Asia                             Retail          1883
44  South America         Manufacturing & Production          1621
45           Asia                       Construction           578
46           Asia                             Mining          1913
47  North America  Distillers, Vintners, & Breweries          1703
48         Europe                  Banking & Finance          1606
49         Europe                   Tourism & Hotels          1230
50         Europe                            Defense          1878
51           Asia                       Conglomerate          1841
52  North America               Aviation & Transport          1870
53         Africa                  Banking & Finance          1892
54         Europe          Cafés, Restaurants & Bars           803
55  South America          Cafés, Restaurants & Bars          1877